### ISSUE TITLE
Provide internal_url and external_url at the same time

### ISSUE THREAD

**Issue by aidistan** [Martin91/paperclip-storage-aliyun#10]
默认的 url 应当跟随配置中的 :internal 选项，但是实际中我们可能同时需要内部地址和外部地址，此时可以考虑给 `Paperclip::Attachment` 添加两个新方法：`internal_url` & `external_url`。

上传时，按服务器位置配置 :internal 选项，按 object key 命名规则配置  :path 即可自动生成 `url`, `internal_url` 和 `external_url`。使用时，可以有：

```ruby
# in photos_controller.rb
@faces = detect_faces(@photo.internal_url) # 使用 internal_url 以节约流量和加快速度
```

```haml
-# in views/photos/show.html.haml
= image_tag(@photo.external_url)
%caption There are #{@faces.count} faces in the above photo.
```

仅作建议：）

**Comment by princemaple** [comment]
both #9 and this seem like something should be implemented in the original paperclip gem https://github.com/thoughtbot/paperclip, not in this extension.

**Comment by aidistan** [comment]
@princemaple

I have a basic idea to solve this problem by utilizing the `style_name` parameter defined in [attachment#url](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L140), which I'm not sure whether it's appropriate.

**Comment by princemaple** [comment]
Could you elaborate your use case about internal url?

**Comment by aidistan** [comment]
There is [an official explanation](https://docs.aliyun.com/?spm=5176.383663.9.13.8BtRU3#/pub/oss/product-documentation/domain-region) why we should use internal urls as much as possible. The `internal` here means the ECSs owned by the same Aliyun account in the same region.

In addition, I would like to implement CDN url retrieves here too.

**Comment by princemaple** [comment]
It's a good idea to implement CDN URL here too, as it's again storage specific.


> why we should use internal urls as much as possible

There is no doubt about that.

`style_name` could be inappropriate, but you could use the options hash I assume?

**Comment by princemaple** [comment]
Internal url is probably only different in terms of host name, and style name most likely determines the path of the url. It's a good thing that they are different, and for that reason I'd say don't use `style_name`

**Comment by aidistan** [comment]
Good reason. I will consider to implement this by the options hash instead.

**Comment by princemaple** [comment]
:+1:

**Comment by Martin91** [comment]
@aidistan Good suggestion, I will also try to implement it if I am free

**Comment by aidistan** [comment]
[Since Paperclip does not pass the option hash to interpolators](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/url_generator.rb#L10), we have to use methods like `aliyun_upload_url` to implement this feature.
