### ISSUE TITLE
when destroy,rails "URI::InvalidURIError: URI must be ascii only"

### ISSUE THREAD

**Issue by lehug** [Martin91/paperclip-storage-aliyun#15]
are you Chinese? if not please view below:
[https://github.com/thoughtbot/paperclip/issues/2286#issuecomment-241943471](more bug messages)

当我用阿里云，并且文件名为中文时，destroy会报错，当我把paperclip-aliyun-configuration删除后，重启项目，文件改为本地存储，这时destroy不会报错，请问此问题应该怎么解决？

**Comment by lehug** [comment]
["/Users/jyd-9062/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:21:in `split'",
 "/Users/jyd-9062/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'",
 "/Users/jyd-9062/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/common.rb:227:in `parse'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:276:in `parse_url'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:280:in `parse_url_with_auth'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:175:in `execute'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient.rb:85:in `head'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/paperclip-storage-aliyun-0.1.0/lib/aliyun/connection.rb:64:in `head'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/paperclip-storage-aliyun-0.1.0/lib/aliyun/connection.rb:146:in `exists?'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/paperclip-storage-aliyun-0.1.0/lib/paperclip/storage/aliyun.rb:36:in `exists?'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:558:in `block in queue_all_for_delete'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:557:in `map'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:557:in `queue_all_for_delete'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/paperclip-4.3.6/lib/paperclip/has_attached_file.rb:93:in `block in add_active_record_callbacks'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `instance_exec'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `block in make_lambda'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:164:in `block in halting'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/mongoid-5.0.2/lib/mongoid/interceptable.rb:138:in `run_callbacks'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/mongoid-5.0.2/lib/mongoid/persistable/destroyable.rb:24:in `destroy'",
 "(pry):29:in `t'",
 "(pry):34:in `<main>'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `eval'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:323:in `handle_line'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `catch'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `block in eval'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:241:in `catch'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_instance.rb:241:in `eval'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/repl.rb:77:in `block in repl'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/repl.rb:67:in `loop'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/repl.rb:67:in `repl'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/repl.rb:38:in `block in start'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/input_lock.rb:79:in `with_ownership'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/repl.rb:38:in `start'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/repl.rb:15:in `start'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-0.10.3/lib/pry/pry_class.rb:169:in `start'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/pry-nav-0.2.4/lib/pry-nav/pry_ext.rb:17:in `start_with_pry_nav'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'",
:MONGODB | 127.0.0.1:27017 | phoenix_development.find | STARTED | {"find"=>"ad_plans", "filter"=>{"workflow_state"=>"paid", "start_day"=>{"$lte"=>2016-08-24 00:00:00 UTC}}}
MONGODB | 127.0.0.1:27017 | phoenix_development.find | SUCCEEDED | 0.000568s
MONGODB | 127.0.0.1:27017 | phoenix_development.find | STARTED | {"find"=>"ad_plans", "filter"=>{"workflow_state"=>"paid", "start_day"=>{"$lte"=>2016-08-24 00:00:00 UTC}}}
MONGODB | 127.0.0.1:27017 | phoenix_development.find | SUCCEEDED | 0.001244s
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'",
 "/Users/jyd-9062/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'",
 "bin/rails:4:in `require'",
 "bin/rails:4:in `<main>'"]

**Comment by aidistan** [comment]
@lehug 试试最新的 `master` 分支，之前修复过一个 bug 一直没发布。
```ruby
gem 'paperclip-storage-aliyun', git: 'https://github.com/Martin91/paperclip-storage-aliyun.git'
```

@Martin91 rspec 的测试用例全挂了，可能是你那边修改了相关的 OSS 配置。能否更新一下？

**Comment by lehug** [comment]
@aidistan 刚试了最新的master，还是依然报这个错误，获取到的path这个String 调用ascii_only?方法抛出的异常

**Comment by aidistan** [comment]
@lehug 了解了，先等 @Martin91 更新一下测试用例吧~

**Comment by Martin91** [comment]
@lehug @aidistan 非常抱歉，刚看到报告，我今晚处理一下

**Comment by Martin91** [comment]
hi @aidistan 测试失败是因为我改了配置，现在先改回来了，测试全部通过；
@lehug 我看了你的问题，也加了测试用例，但是无法重现你说的问题，你的问题是得到了一条错误的路径信息，但是我看了我们的代码，整个过程中并不会 escape 路径信息，所以我怀疑问题是出在其他组件上，现在已经太晚，我只能明天晚上再看这个问题了。

**Comment by Martin91** [comment]
@aidistan @lehug 我推了个分支 `fix-#15`

**Comment by aidistan** [comment]
@lehug 拉取一下 `fix-#15` 分支，在里面重现一下遇到的问题吧～

**Comment by Martin91** [comment]
@lehug 我这边无法完全重现，但是找到了一个可能的原因并且已经修复，请看
https://github.com/Martin91/paperclip-storage-aliyun/commit/21ddf16562cc3b7aeaec45e91694486f37d315e1

@aidistan 原因出在原来的 `Aliyun::Connection#path_to_url(path)` 代码没有确保不管是绝对路径还是相对路径，都应该执行 `URI.encode` ，导致存在出现 `URI::InvalidURIError` 错误的可能。
请看上面贴的链接里的代码。

**Comment by lehug** [comment]
谢谢，问题解决，这是我第一次提交bug，感谢帮助纠结，感觉很好 👍

**Comment by aidistan** [comment]
这个问题是我引入 #14 中代码时的疏忽所致，抱歉 :stuck_out_tongue_winking_eye:

**Comment by Martin288** [comment]
@lehug 欢迎多反馈意见，因为这个 repo 我自己现在没用到，所以没法及时发现问题，但是有问题报告，我们会尽快修复。
@aidistan 没事，问题根源在于我完全没有执行 uri 编码，你仍然还是帮忙解决了问题的。感谢！
