### ISSUE TITLE
Unable to fetch image

### ISSUE THREAD

**Issue by mehdi-farsi** [Martin91/paperclip-storage-aliyun#17]
HI

I'm able to upload an image. Othewise, The URL returned by `Image.source.url` is `https://mybucket.oss-ap-southeast-1.aliyuncs.com?1474196962` and not the url to the uploaded picture.

Gemfile:

```ruby
gem 'paperclip-storage-aliyun', github: 'Martin91/paperclip-storage-aliyun'
```

paperclip.rb

```ruby
Paperclip::Attachment.default_options[:aliyun] = {
  access_id: ENV['ALIYUN_ACCESS_ID'],
  access_key: ENV['ALIYUN_ACCESS_KEY'],
  bucket: 'mybucket',
  data_center: 'oss-ap-southeast-1',
  internal: false
}
```

image.rb

```ruby
  attr_accessor :source_file_name, :delete_source

  has_attached_file :source, {
    storage: :aliyun,
    path: ':class/:attachment/:id_partition/:filename',
    url: 'https://mybucket.oss-ap-southeast-1.aliyuncs.com'
  }
  before_validation { self.source.clear if self.delete_source == '1' }

  validates_attachment_content_type :source, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
```

**Comment by Martin91** [comment]
@mehdi-farsi thanks for reporting this issue, I will debug and try to reproduce the error ASAP. BTW, what is your filename?

**Comment by mehdi-farsi** [comment]
Thanks for your reactivity.
The filename is `25.png`

**Comment by Martin91** [comment]
@mehdi-farsi ok, thanks so much

**Comment by mehdi-farsi** [comment]
Further information about my bucket configuration:

- the ACL or my OSS bucket is `public read`
-No CORS
- OSS Internet domain name: mybucket.oss-ap-southeast-1.aliyuncs.com
- I'm testing locally with a basic Webrick server.

**Comment by Martin91** [comment]
@mehdi-farsi it seems that you have a mistake in the usage of url option:
```ruby
  has_attached_file :source, {
    storage: :aliyun,
    path: ':class/:attachment/:id_partition/:filename',
    url: 'https://mybucket.oss-ap-southeast-1.aliyuncs.com'
  }
```
according to the document at https://github.com/Martin91/paperclip-storage-aliyun#configuration:
> Similar to Paperclip::Storage::S3, there are four options for the url by now:
>
>* `:aliyun_upload_url` : the url based on the options you give  
>* `:aliyun_internal_url` : the internal url, no matter what options[:aliyun][:internal] is  
>* `:aliyun_external_url` : the external url, no matter what options[:aliyun][:internal] is  
>* `:aliyun_alias_url` : the alias url based on the host_alias you give, typically used together with CDN 
>
> Please note the values above are all strings, not symbols. You could still make your own url if only you know what you are doing.

but you used a hardcoded string besides one of the above four available values. Could you please retry according the README again? Please feel free to leave further comment if the problem still exists.

**Comment by mehdi-farsi** [comment]
That works ! My bad !

Thanks ! 👍 

You can close the issue

**Comment by Martin91** [comment]
@mehdi-farsi so sorry for our confusing README, I will try to avoid any ambiguity. Feel free to contact us if any other problem.
