### ISSUE TITLE
Empty directory after gem installs

### ISSUE THREAD

**Issue by tiaozi0912** [Martin91/paperclip-storage-aliyun#2]
这个gem在bundle install 以后并没有被fetch下来，整个paperclip-storage-aliyun-0.0.2的directory是空的。

**Comment by International** [comment]
Any updates on this bug?

**Comment by Martin91** [comment]
@tiaozi0912 @International Has fixed and released a new version 0.0.3, please update to the newest version, in this version, I have resolved a few known issues and update the specs.
