### ISSUE TITLE
Aliyun protocol

### ISSUE THREAD

**Issue by 7a6163** [Martin91/paperclip-storage-aliyun#24]
Do you think about to add an empty string option for Aliyun protocol?
Setting an empty string to generate protocol-relative URLs.

**Comment by Martin91** [comment]
It sounds like a reasonable requirement, will do it later

**Comment by Martin91** [comment]
implemented in https://github.com/Martin91/paperclip-storage-aliyun/releases/tag/v0.1.5 @7a6163
