### ISSUE TITLE
data_center参数值被改变引起的bug

### ISSUE THREAD

**Issue by cnhuye** [Martin91/paperclip-storage-aliyun#25]
data_center.rb#33
代码:  data_center.prepend('oss-')
会直接修改传递过来的值如"cn-beijing"为 "oss-cn-beijing"，
但传递过来的参数，通常是在全局设置的CONFIG，如下:
```
...
data_center: CONFIG['aliyun_data_center'],
...
```
所以外部代码在不知情的情况下， CONFIG['aliyun_data_center'] 值就被修改了，导致其它地方出错。
建议这里不要直接修改传递过来的参数值本身。使用  data_center = 'oss-' + data_center 这样的方式。

**Comment by Martin91** [comment]
好建议，会尽快处理。
