### ISSUE TITLE
Relative path returned by model.attachment.url method

### ISSUE THREAD

**Issue by tiaozi0912** [Martin91/paperclip-storage-aliyun#3]
还遇到一个问题：
user has attachment named photo, user.photo.url 返回了一个relative的path, 如

/advisor_2/created_at_1369288191/original.jpg?1413099173
而不是绝对的url。 我想应该expect返回的是绝对的url吧

**Comment by Martin91** [comment]
@tiaozi0912 这个问题无法重现，是否依旧存在？

**Comment by aidistan** [comment]
这应该是没有自定义 :url，而使用了默认 :url 出现的问题。

**Comment by tiaozi0912** [comment]
是因为我在url里面定义了relative的url
