### ISSUE TITLE
Can't set content type in Aliyun storage

### ISSUE THREAD

**Issue by tiaozi0912** [Martin91/paperclip-storage-aliyun#6]
There is no options in the oss_connection.put method:
https://github.com/Martin91/paperclip-storage-aliyun/blob/master/lib/paperclip/storage/aliyun.rb#L13

So the content type will be always set as "image/jpg":
https://github.com/Martin91/paperclip-storage-aliyun/blob/master/lib/aliyun/connection.rb#L45

If uploading a pdf file, for example, the MimeType is still "image/jpg". But it should be "application/pdf"

**Comment by Martin91** [comment]
@tiaozi0912 This is finished in v0.0.3, thanks for your report and so sorry for my delay working.
