### ISSUE TITLE
Require a graceful way to define default url style of attachments

### ISSUE THREAD

**Issue by aidistan** [Martin91/paperclip-storage-aliyun#8]
*README.md* 示例使用了 `has_attached_file` 的参数来定义的 url 风格，此时在模型中 `include Paperclip::Storage::Aliyun` 尚可接受。但若希望设定全局默认 url 风格时，将众多方法 extend 到 main 对象中未免有些不妥：

```ruby
# config/initializers/paperclip.rb

include Paperclip::Storage::Aliyun

Paperclip::Attachment.default_options[:aliyun] = {
  access_id: ENV['ALIYUN_ACCESS_ID'],
  access_key: ENV['ALIYUN_ACCESS_KEY'],
  #...
}

Paperclip::Attachment.default_options[:path] = (Rails.env.production? ? '' : ':rails_env') + '/:class/:attachment/:id.:extension'
Paperclip::Attachment.default_options[:url] = 'http://' + oss_connection.fetch_file_host + '/' + Paperclip::Attachment.default_options[:path]
```

事实上 `Paperclip::Attachment.default_options[:aliyun]` 已经唯一地决定了 `Aliyun::Connect#fetch_file_host` 的结果，而与具体实例无关，此处可以有一个类方法帮助我们更优雅地配置全局默认 url 风格。

**Comment by Martin91** [comment]
感谢反馈，我在上班，我业余时间处理一下这个问题，之前也觉得到处 extend 有坏味道，但是上次发版本时忘了包含这个任务！

**Comment by aidistan** [comment]
应该的：），您的 Gem 省了我很多事，必须支持呀！

**Comment by aidistan** [comment]
最近我可能可以抽出点时间，希望能为这个项目添砖加瓦。不知道您有什么意见和建议？先与您沟通一下是为了提高 PR 通过的成功率 :smile:

**Comment by Martin91** [comment]
非常感谢！我暂时没有意见，只要功能正常，以及使用起来顺手，代码简洁规即可！
Aidi Stan <notifications@github.com>于2015年10月9日 周五下午3:52写道：
