### ISSUE TITLE
Allow local credentials overiwriting global default credentials

### ISSUE THREAD

**Issue by aidistan** [Martin91/paperclip-storage-aliyun#9]
目前 paperclip-storage-aliyun 每次建立 OSS 连接都使用了默认配置：

```ruby
oss_connection ||= ::Aliyun::Connection.new Paperclip::Attachment.default_options[:aliyun]
```

我们可以更灵活地支持在模型定义 `has_attached_file` 时覆盖默认配置，例如：

```ruby
#  paperclip-storage-aliyun/lib/paperclip/storage/aliyun.rb
oss_connection ||= ::Aliyun::Connection.new Paperclip::Attachment.default_options[:aliyun].merge(local_options)
```

这样我们就可以有

```ruby
has_attached_file :download, storage: :aliyun, aliyun: { bucket: 'another-place'}
has_attached_file :secret, storage: :aliyun, aliyun: { access_id: 'another-id', access_key: 'another-key', bucket: 'secret-place'}
```

**Comment by aidistan** [comment]
Nope, I can't agree with you. This issue is solved pretty well in the [Paperclip::Storage::S3](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb).

The basic idea is
1. [to merge global options and local options to get each attachment's options](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb#L269)
2. [to initialize each attachment's own storage connection by the options we get in step 1](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb#L278)

**Comment by princemaple** [comment]
@aidistan True. You are right actually. I said that too fast without enough reading. Thought the core gem would have some centralized solution but on a second thought, it's indeed storage specific. :+1:

**Comment by Martin91** [comment]
@aidistan Sounds great and worth having a try, but I am too busy to do this, if you are willing to finish it?Maybe I can try to implement it if I am free, but I am afraid that it will be a long time later.

**Comment by aidistan** [comment]
@Martin91 OK, I'll take care of that. But may I import EditorConfig for style organization (use two spaces instead of tabs) and Travis for continue integration (make sure our specs never fail)?
